import * as React from 'react';
import Head from 'next/head';
import Layout from '../../../components/Layout/Layout';
import { IPageProps } from '../../_app';
import OrderLicense from '../../../components/Order/OrderLicense/OrderLicense';
import ILicense from '../../../helper/types/products/License/plan';

interface IProps extends IPageProps {
  status: boolean;
  plan: ILicense;
}

class Index extends React.Component<IProps> {
  render() {
    return (
      <div dir="rtl">
        <Head>
          <title>خرید لایسنس</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Layout header={this.props.header} footer={this.props.footer}>
          <OrderLicense plan={this.props.plan} />
        </Layout>
      </div>
    );
  }
}

export async function getServerSideProps(context) {
  const locale = context.locale;
  const id = context.query.id;

  if (locale !== 'fa') {
    return {
      notFound: true,
    };
  }

  const respone = await fetch(
    `${process.env.SITE_URL}/${locale}/order/licenses/${id}?ajax=1`
  );
  const data = await respone.json();

  if (!data.status) {
    return {
      notFound: true,
    };
  }

  return {
    props: { ...data },
  };
}

export default Index;
