import * as React from 'react';
import Head from 'next/head';
import OrderDomain from '../../../../components/Order/OrderDomain';
import { connect } from 'react-redux';
import Layout from '../../../../components/Layout/Layout';
import { IPageProps } from '../../../_app';
import { getForConfigureDomains } from '../../../../store/Domain';

interface IProps extends IPageProps {
  domains: any;
  nationalDomainsList: any;
  getForConfigureDomains: typeof getForConfigureDomains;
}

class Index extends React.Component<IProps> {
  componentDidMount() {
    this.props.getForConfigureDomains();
  }

  render() {
    return (
      <div dir="rtl">
        <Head>
          <title>پیکربندی دامنه ها</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Layout header={this.props.header} footer={this.props.footer}>
          <OrderDomain step="configuration" />
        </Layout>
      </div>
    );
  }
}

export async function getServerSideProps(context) {
  const locale = context.locale;

  if (locale !== 'fa') {
    return {
      notFound: true,
    };
  }

  const respone = await fetch(
    `${process.env.SITE_URL}/${locale}/order/domain/configure?ajax=1`
  );
  const data = await respone.json();

  return {
    props: { ...data },
  };
}

export default connect(null, { getForConfigureDomains })(Index);
