import * as React from 'react';
import Head from 'next/head';
import Layout from '../components/Layout/Layout';
import { pageProps } from './_app';
import Jobs from '../components/Jobs/Jobs';

export interface IndexProps extends pageProps {
  postsForFooter: any;
  jobs: any;
}

export interface IndexState {}

class Index extends React.Component<IndexProps, IndexState> {
  constructor(props: IndexProps) {
    super(props);
    this.state = {};
  }
  render() {
    return (
      <div dir="rtl">
        <Head>
          <title>فرصت های شغلی</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Layout
          postsForFooter={this.props.postsForFooter}
          domainsForNavbar={this.props.domainsForNavbar}
        >
          <Jobs jobs={this.props.jobs} />
        </Layout>
      </div>
    );
  }
}

export async function getServerSideProps(context) {
  const locale = context.locale;

  if (locale !== 'fa') {
    return {
      notFound: true,
    };
  }

  const postsForFooterRes = await fetch(
    'https://jsonblob.com/api/jsonBlob/ff048401-e7cd-11eb-971c-9ff88820de62'
  );
  const postsForFooter = await postsForFooterRes.json();

  const jobsRes = await fetch(
    'https://jsonblob.com/api/jsonBlob/e127214d-eada-11eb-8813-490a330e4ec5'
  );
  const jobs = await jobsRes.json();

  return {
    props: { postsForFooter, jobs },
  };
}

export default Index;
