import * as React from 'react';
import Head from 'next/head';
import ServerDedicated from '../../components/Dedicated/ServerDedicated';
import Layout from '../../components/Layout/Layout';
import { IPageProps } from './../_app';

interface IProps extends IPageProps {
  status: boolean;
  countries: { code: string; name: string; is_recommended: boolean }[];
}

class Index extends React.Component<IProps> {
  render() {
    return (
      <div dir="rtl">
        <Head>
          <title>سرور اختصاصی</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Layout header={this.props.header} footer={this.props.footer}>
          <ServerDedicated countries={this.props.countries} />
        </Layout>
      </div>
    );
  }
}

export async function getServerSideProps(context) {
  const locale = context.locale;

  if (locale !== 'fa') {
    return {
      notFound: true,
    };
  }

  const respone = await fetch(
    `${process.env.SITE_URL}/${locale}/server/dedicated?ajax=1`
  );
  const data = await respone.json();

  return {
    props: {
      ...data,
    },
  };
}

export default Index;
